services:
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datalma
      PGPORT: 6543
    ports:
      - "6543:6543"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:6543/datalma
    ports:
      - "7777:7777"
    volumes:
      - .:/app
      - "/app/staticfiles"
    depends_on:
      - db

volumes:
  postgres_data:
